/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xF6, 0x24, 0xF4, 0x83, 0xB1, 0x4B, 0xE2, 0xB4}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 3 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 3 }

#define VIAL_TAP_DANCE_ENTRIES 9
#define VIAL_COMBO_ENTRIES     9

#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define DYNAMIC_KEYMAP_MACRO_COUNT 12
#define TAPPING_TERM 560
#define TAPPING_TOGGLE 3
#define PERMISSIVE_HOLD

#define MASTER_LEFT
#undef PMW33XX_LIFTOFF_DISTANCE
#define PMW33XX_LIFTOFF_DISTANCE 0x04
#undef POINTING_DEVICE_TASK_THROTTLE_MS
#define POINTING_DEVICE_TASK_THROTTLE_MS 1
#undef CHARYBDIS_MINIMUM_DEFAULT_DPI
#define CHARYBDIS_MINIMUM_DEFAULT_DPI 600

#undef ROTATIONAL_TRANSFORM_ANGLE
#define ROTATIONAL_TRANSFORM_ANGLE -35
